<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Adp.Agents</RootNamespace>
    <AssemblyName>Adp.Agents</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1701;NU1702</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.AI.Agents.Persistent" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PackageModel\PackageModel.csproj" />
    <ProjectReference Include="..\ToolRuntime\ToolRuntime.csproj" />
  </ItemGroup>
</Project>
