<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Adp.ContextLayer</RootNamespace>
    <AssemblyName>Adp.ContextLayer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.Search.Documents" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
</Project>
