<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Adp.DecisionIngest</RootNamespace>
    <AssemblyName>Adp.DecisionIngest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
